In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('C:/Users/mahid/Desktop/suchi.csv')

In [4]:
df.head()

,TransactionId,TransactionDate,Tour,Round,Amount,Description
0,JL2021061502450116538067,2021-06-15T02:45:01.000Z,World Test Championship- Final,IND VS NZ (18-June-2021),60,Joined A Contest
1,JL2021061013524616538067,2021-06-10T13:52:46.000Z,West Indies vs South Africa Test,WI VS SA (10-June-2021),19,Joined A Contest
2,JL2021061013524616538067,2021-06-10T13:52:46.000Z,West Indies vs South Africa Test,WI VS SA (10-June-2021),19,Promotion Granted
3,WCB2021053101301616538067,2021-05-31T01:30:16.000Z,NaN,NaN,48,Cash Bonus Expired
4,JL2021052506501116538067,2021-05-25T06:50:11.000Z,Bangladesh vs Sri Lanka ODI,BAN VS SL (25-May-2021),35,Joined A Contest

In [5]:
dataset=df['Amount']

In [6]:
df1=df[['Amount', 'Description']]

In [7]:
df1.head()

   Amount         Description
0      60    Joined A Contest
1      19    Joined A Contest
2      19   Promotion Granted
3      48  Cash Bonus Expired
4      35    Joined A Contest

In [8]:
for i in df['Description']:
    print(i)

Joined A Contest
Joined A Contest
Promotion Granted
Cash Bonus Expired
Joined A Contest
Won A Contest
Joined A Contest
Cash Bonus Expired
Cash Bonus Expired
Level Up Cash Bonus Credited
Cash Bonus Expired
Cash Bonus Expired
Withdrew Cash
Cash Bonus Expired
Deposit Cash Bonus
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Level Up Cash Bonus Credited
Won A Contest
Joined A Contest
Joined A Contest
Won A Contest
Promotion Granted
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Won A Contest
Won A Contest
Joined A Contest
Promotion Granted
Joined A Contest
Joined A Contest
Won A Contest
Won A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Won A Contest
Won A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Won A Contest
Won A Contest
Won A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Deposit Cash Bonus
Joined A Contest
Deposited Cash
Joined A Contest
Withdrew Cash
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Won A Contest
Won A Contest
Joined A Contest
Joined A Contest
Promotion Granted
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Won A Contest
Joined A Contest
Won A Contest
Joined A Contest
Won A Contest
Joined A Contest
Won A Contest
Won A Contest
Joined A Contest
Joined A Contest
Won A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Cash Bonus Expired
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Cash Bonus Expired
Deposit Cash Bonus
Joined A Contest
Won A Contest
Joined A Contest
Deposit Cash Bonus
Deposited Cash
Withdrew Cash
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Refunded
Joined A Contest
Won A Contest
Joined A Contest
Promotion Granted
Joined A Contest
Promotion Granted
Joined A Contest
Promotion Granted
Won A Contest
Promotion Granted
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Won A Contest
Won A Contest
Joined A Contest
Joined A Contest
Won A Contest
Joined A Contest
Joined A Contest
Joined A Contest
Joined A Contest

In [9]:
win1=0
for index,row in df.iterrows():
    if(row['Description']=="Deposited Cash"):
        win1=win1+row['Amount']

In [10]:
win2=0
for index,row in df.iterrows():
    if(row['Description']=="Withdrew Cash"):
        win2=win2+row['Amount']

In [11]:
total_winnings=win2-win1

In [12]:
print(total_winnings)

2000

In [19]:
win3=0
win4=0
win5=0
for index,row in df.iterrows():
    if(row['Description']=="Won A Contest"):
        win3=win3+row['Amount']
    if(row['Description']=="Joined A Contest"):
        win4=win4+row['Amount']
    if(row['Description']=="Promotion Granted" or row['Description']=="Level Up Cash Bonus Credited" or row['Description']=="Deposit Cash Bonus" ):
        win5=win5+row['Amount']

In [22]:
total=win3-win4+win5
print(total)

1539